import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import SideBar from "@/ui/SideBar/SideBar";
import NavBar from "@/ui/NavBar/NavBar";
import BottomBar from "@/ui/BottomBar/BottomBar";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`${lato.className} relative overflow-x-clip`}>
          <NavBar />
          <div className={"w-full h-auto md:flex md:justify-start"}>
            <SideBar />
            {children}
          </div>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
